version: '2.1'

services:
  ezpc-MySQL:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: easypc
      MYSQL_USER: root
    ports:
      - "3307:3306"
    networks:
      - routine-net
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_ROOT_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15

  

networks:
  routine-net:
    driver: bridge